## Vertices of a rectangle

In [2]:
# This code computes the vertices of a rectangle given a normal vector to the plane and one point on the plane

import numpy as np

# Define the normal vector and a point on the plane
normal = np.array([1, 0, 0])
point_on_plane = np.array([0, 0, 0])

# Normalize the normal vector
normal = normal / np.linalg.norm(normal)

# Compute two orthogonal vectors that lie on the plane
v1 = np.array([0, 1, 0])
v2 = np.cross(normal, v1)
v2 /= np.linalg.norm(v2)
v1 = np.cross(v2, normal)

# Define the length and width of the rectangle
length = 2
width = 1

# Compute the half-length and half-width
half_length = length / 2
half_width = width / 2

# Compute the center point of the rectangle
center = point_on_plane + half_length * v1 + half_width * v2

# Compute the vertices of the rectangle
vertex1 = center + half_length * v1 + half_width * v2
vertex2 = center + half_length * v1 - half_width * v2
vertex3 = center - half_length * v1 - half_width * v2
vertex4 = center - half_length * v1 + half_width * v2

print(vertex1, vertex2, vertex3, vertex4)


[0. 2. 1.] [0. 2. 0.] [0. 0. 0.] [0. 0. 1.]


## Discretization

In [1]:
import numpy as np

# Define the size of the continuous plane
width = 10
height = 10

# Define the size of the grid of cells
n_cells_x = 5
n_cells_y = 5

# Compute the size of each cell
cell_size_x = width / n_cells_x
cell_size_y = height / n_cells_y

# Create a grid of cell centers
cell_centers_x = np.linspace(cell_size_x/2, width-cell_size_x/2, n_cells_x)
cell_centers_y = np.linspace(cell_size_y/2, height-cell_size_y/2, n_cells_y)
cell_centers = np.meshgrid(cell_centers_x, cell_centers_y)
cell_centers = np.stack(cell_centers, axis=-1)

# Display the cell centers
print(cell_centers)


[[[1. 1.]
  [3. 1.]
  [5. 1.]
  [7. 1.]
  [9. 1.]]

 [[1. 3.]
  [3. 3.]
  [5. 3.]
  [7. 3.]
  [9. 3.]]

 [[1. 5.]
  [3. 5.]
  [5. 5.]
  [7. 5.]
  [9. 5.]]

 [[1. 7.]
  [3. 7.]
  [5. 7.]
  [7. 7.]
  [9. 7.]]

 [[1. 9.]
  [3. 9.]
  [5. 9.]
  [7. 9.]
  [9. 9.]]]
